version: '3.8'

services:
  news-bot:
    container_name: news-bot
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - NEWS_TBOT_WEBHOOK=${NEWS_TBOT_WEBHOOK}
      - NEWS_TBOT_NAME=${NEWS_TBOT_NAME}
      - NEWS_TBOT_TOKEN=${NEWS_TBOT_TOKEN}
      - NEWS_TBOT_DB_USER=${NEWS_TBOT_DB_USER}
      - NEWS_TBOT_DB_PASSWORD=${NEWS_TBOT_DB_PASSWORD}
      - NEWS_TBOT_DB_URL=${NEWS_TBOT_DB_URL}
    build: .
    restart: always
    ports:
      - "2010:2010"
      - "2110:2110"
    depends_on:
      - postgresql
#      - ngrok
  postgresql:
    image: 'postgres:15.5-bullseye'
    container_name: postgresql
    environment:
      - POSTGRES_USER=${NEWS_TBOT_DB_USER}
      - POSTGRES_PASSWORD=${NEWS_TBOT_DB_PASSWORD}
      - POSTGRES_DB=tbot
    ports:
      - "5432:5432"
#  ngrok:
#    image: ngrok/ngrok:latest
#    environment:
#      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
#      NGROK_URL: ${NGROK_URL}
#    command: 'http --domain=${NGROK_URL} host.docker.internal:2010'
#    ports:
#      - "4040:4040"