service-settings:
  name: "News Telegram Bot"
  version: "0.0.1"
  scheduler:
    cron: "0 0 8 * * *"
#    cron: "0 * * * * *"
server:
  port: 2010

telegram:
  api-url: https://api.telegram.org
  webhook-path: ${NEWS_TBOT_WEBHOOK}
  bot-name: ${NEWS_TBOT_NAME}
  bot-token: ${NEWS_TBOT_TOKEN}

spring:
  datasource:
    username: ${NEWS_TBOT_DB_USER}
    password: ${NEWS_TBOT_DB_PASSWORD}
    url: ${NEWS_TBOT_DB_URL}
  flyway:
    enabled: true
    user: ${NEWS_TBOT_DB_USER}
    password: ${NEWS_TBOT_DB_PASSWORD}
    url: ${NEWS_TBOT_DB_URL}
    locations: classpath:db.migration