service-settings:
  name: "News Telegram Bot"
  version: "0.0.1"

server:
  port: 2010

telegram:
  api-url: https://api.telegram.org
  webhook-path: test
  bot-name: ${NEWS_TBOT_NAME}
  bot-token: ${NEWS_TBOT_TOKEN}
